# -*- coding: utf-8 -*-
"""
Created on Wed Apr 29 18:43:30 2026

@author: cns-th-lab
"""

import h5py
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

def get_nan_proportions(h5_path):
    """
    Loads a SLEAP .h5 file and calculates the proportion of NaN frames per node.
    """
    with h5py.File(h5_path, 'r') as f:
        # Load the tracks array. Native shape is (instances, dims, nodes, frames)
        tracks = f['tracks'][:]
        
        # Try to extract the actual node names if they exist in the file
        if 'node_names' in f:
            # SLEAP stores these as byte strings, so we decode them
            node_names = [n.decode('utf-8') for n in f['node_names'][:]]
        else:
            # Fallback if names are missing
            node_names = [f"Node {i}" for i in range(tracks.shape[2])]

    # Isolate Instance 0, Dimension 0 (X coordinate). Shape becomes (nodes, frames)
    # If the X coordinate is NaN, the Y coordinate is also NaN, so checking one is sufficient.
    print(np.shape(tracks))
    node_data = tracks[0, 0, :, :]
    
    total_frames = node_data.shape[1]
    
    # Sum the NaNs across the frames axis (axis=1) for each node
    nan_counts = np.isnan(node_data).sum(axis=1)
    print(np.shape(nan_counts))
    
    # Calculate the proportion (0.0 to 1.0)
    nan_proportions = nan_counts / total_frames
    
    return nan_proportions, node_names

def plot_nan_comparison(stripped_path, interpolated_path):
    """
    Plots the NaN proportions of the stripped vs. interpolated data.
    """
    print(f"Loading data...")
    prop_stripped, node_names = get_nan_proportions(stripped_path)
    quit()
    prop_interp, _ = get_nan_proportions(interpolated_path)
    print(prop_stripped)
    print(prop_interp)
    
    nodes_count = len(node_names)
    x_indices = np.arange(nodes_count)
    
    print("Generating plot...")
    plt.figure(figsize=(12, 7))
    
    # Plot both lines
    plt.plot(x_indices, prop_stripped, marker='o', color='crimson', linewidth=2, markersize=8, label='Pre-Interpolation (Stripped)')
    plt.plot(x_indices, prop_interp, marker='^', color='teal', linewidth=2, markersize=8, label='Post-Interpolation (Smoothed)')
    
    # Fill the area between the lines to visually highlight the recovered data
    plt.fill_between(x_indices, prop_interp, prop_stripped, color='teal', alpha=0.1, label='Data Recovered')

    # Formatting
    plt.title('Proportion of NaN Frames per Node: Before vs. After Interpolation', fontsize=14, pad=15)
    plt.xlabel('Body Part (Node)', fontsize=12)
    plt.ylabel('Proportion of NaNs (0.0 to 1.0)', fontsize=12)
    
    # Apply node names to the X-axis and angle them so they don't overlap
    plt.xticks(x_indices, node_names, rotation=45, ha='right')
    
    # Set Y-axis limits slightly wider than 0-1 for padding
    plt.ylim(-0.05, 1.05)
    
    plt.grid(True, alpha=0.4, linestyle='--')
    plt.legend(fontsize=11)
    plt.tight_layout()
    
    plt.show()

if __name__ == "__main__":
    # Define your paths
    base_dir = Path(r"C:\Users\cns-th-lab\SLEAP_Labels_4_29_26\198\Videos")
    
    # Ensure these match the actual filenames generated by your pipeline
    file_stripped = base_dir / "198.2025-07-28.mov_0002.proj_STRIPPED.h5"
    file_interpolated = base_dir / "198.2025-07-28.mov_0002.proj_INTERPOLATED.h5"
    
    if file_stripped.exists() and file_interpolated.exists():
        plot_nan_comparison(file_stripped, file_interpolated)
    else:
        print("Error: Could not find one or both of the .h5 files. Please check the file paths.")
#%%
investigating_h5 = r"C:\Users\cns-th-lab\SLEAP_Labels_4_29_26\198\Videos\198.2025-07-28.mov_0001.proj_STRIPPED.h5"
with h5py.File(investigating_h5, 'r') as f:
     # Load the tracks array. Native shape is (instances, dims, nodes, frames)
     tracks = f['tracks'][:]
     node_names = [n.decode('utf-8') for n in f['node_names'][:]]
     print(np.shape(tracks[0,:,:,0]))
    